image: node:18.4.0

pipelines:
  default:
    - step:
        name: Build
        script:
          - npm install
          - npm run prepublishOnly
    - step:
        name: Publish
        deployment: production
        script:
          - npm run preversion
          - npm version patch -m "Upgrade to version %s [skip ci]"
          - git push && git push --tags
          - pipe: atlassian/npm-publish:0.2.0
            variables:
              NPM_TOKEN: $NPM_TOKEN
