name: Release
on:
  push:
    branches: [main, dev]
concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false
jobs:
  release:
    uses: erik7z/deployments/.github/workflows/reusable-semantic-release.yml@v1
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
